version: '3'
services:

  #web:
    #build: .
    #volumes:
      #- .:/opt/meatball
    #ports:
      #- "3006:4567"
    #env_file:
      #- .env

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    volumes:
      - .:/opt/meatball
    env_file:
      - .env
    restart: unless-stopped
