FROM ruby:2.7-alpine

RUN apk add --update \
  less \
  python3 \
  build-base \
  libxml2-dev \
  libxslt-dev \
  && rm -rf /var/cache/apk/*

RUN pip3 install markovify

RUN mkdir -p /opt/meatball
WORKDIR /opt/meatball

COPY Gemfile /opt/meatball
COPY Gemfile.lock /opt/meatball
RUN bundle install

VOLUME /opt/meatball

RUN echo '30 5 * * * cd /opt/meatball && ruby autolearn.rb' >> /etc/crontabs/root
RUN echo '0 * * * * cd /opt/meatball && ruby tweet.rb' >> /etc/crontabs/root

CMD ["/usr/sbin/crond", "-f", "-d", "0"]
