version: '3'
services:

  web:
    build: .
    volumes:
      - .:/opt/meatball
    ports:
      - "3006:4567"

  cron:
    build:
      context: .
      dockerfile: Dockerfile-cron
    volumes:
      - .:/opt/meatball
